### ISSUE TITLE
equal.c does not work when the last char is different

### ISSUE THREAD

**Issue by benjamin051000** [dankeyy/shitposting#1]
Consider this watered-down example:
```c
#include <stdio.h>

eql (char *a, char *b) {
    (a == b) || ({while (*a && *b && *a++ == *b++); !*a && !*b;});
}

int main() {
    char* a = "abc";
    char* b = "abz";

    printf(eql(a, b) ? "true\n" : "false\n");
}
```

[compiler explorer](https://godbolt.org/z/7vs9Y6ofd) shows `true` as the output.

**Comment by benjamin051000** [comment]
Also, a segmentation fault occurs when one input is NULL and the other is not. 

I still have no clue how you are returning values here, since [implicit return values are undefined](https://stackoverflow.com/questions/10079089/implicit-int-return-value-of-c-function). I wonder if gcc simply returns the value of eax or rax, and the ops you do in the function modify that register.

**Comment by benjamin051000** [comment]
Is it possible to solve either of these bugs? Otherwise, it seems to work pretty well. I'd approve this in a code review. 👍

**Comment by benjamin051000** [comment]
```c
eql (char *a, char *b) {
    (a == b) || ({while (*a && *b && *a == *b) {a++; b++;}; !*a && !*b;});
}
```
This appears to solve the first problem. I haven't fully tested it, though.

The difference between this while loop and the original is that if `*a != *b`, they are not incremented. It's late and I am not sure if this is sound logic. I will look again tomorrow and try to figure out if this actually makes sense, or if it's just a fluke that it passes the test case.

**Comment by dankeyy** [comment]
thanks fellow shitposter, solved all mentioned issues by latest commit
